### ISSUE TITLE
dump data failed with syntax error when the entire table is generated columns

### ISSUE THREAD

**Issue by aytrack** [pingcap/dumpling#145]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
```
dumpling -o . -P 4000 -u root -h host
```
2. What did you expect to see?
dump data successfully.
3. What did you see instead?
```
[2020/08/27 14:42:01.739 +08:00] [ERROR] [main.go:212] ["dump failed error stack info"] [error="SELECT  FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 12 near \"FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1\" "] [errorVerbose="err = SELECT  FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 12 near \"FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1\" \ngoroutine 1 [running]:\nruntime/debug.Stack(0x19aec00, 0xc000272f40, 0x19afec0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/pingcap/dumpling/v4/export.withStack(0x19aec00, 0xc000272f40, 0xc00018a000, 0xc0001a2c00)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/error.go:59 +0x8f\ngithub.com/pingcap/dumpling/v4/export.GetColumnTypes(0xc000304180, 0x0, 0x0, 0xc00023ffe0, 0x18, 0x1dd1720, 0x1, 0x0, 0x0, 0x0, ...)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/sql.go:263 +0x325\ngithub.com/pingcap/dumpling/v4/export.SelectAllFromTable(0xc00029e000, 0xc000304180, 0xc00023ffe0, 0x18, 0x1dd1720, 0x1, 0x1, 0xc00001a000, 0xcf, 0x0)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/sql.go:141 +0x105\ngithub.com/pingcap/dumpling/v4/export.dumpTable(0x19c4cc0, 0xc0001a8cc0, 0xc00029e000, 0xc000304180, 0xc00023ffe0, 0x18, 0xc0003a1e00, 0x19c32c0, 0xc00029e000, 0xc0003f5350, ...)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/dump.go:321 +0xc5\ngithub.com/pingcap/dumpling/v4/export.dumpDatabases(0x19c4cc0, 0xc0001a8cc0, 0xc00029e000, 0xc00031e0e0, 0x19c32c0, 0xc00029e000, 0x0, 0x0)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/dump.go:232 +0x353\ngithub.com/pingcap/dumpling/v4/export.Dump(0x19c4d00, 0xc00018a000, 0xc00029e000, 0x0, 0x0)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/dump.go:199 +0xc25\nmain.main()\n\t/Users/aytrack/gitproject/pingcap/dumpling/cmd/dumpling/main.go:210 +0x152a\n"] [stack="github.com/pingcap/dumpling/v4/log.Error\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/log/log.go:78\nmain.main\n\t/Users/aytrack/gitproject/pingcap/dumpling/cmd/dumpling/main.go:212\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204"]

dump failed: SELECT  FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 12 near "FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1"   
```
4. Versions of the cluster

    - Dumpling version (run `dumpling -V`):

        ```
        Release version: v4.0.3-12-g8e00b82
        Git commit hash: 8e00b826f68dda6734d69d7d5c96d082b0e88ee6
        Git branch:      master
        Build timestamp: 2020-08-27 06:25:31Z
        Go version:      go version go1.15 darwin/amd64
        ```

    - Source database version (execute `SELECT version();` in a MySQL client):

        ```
        +-------------------------------------------------------------------+
        | tidb_version()                                                    |
        +-------------------------------------------------------------------+
        | Release Version: v4.0.0-beta.2-1006-g6831e487a                    |
        | Edition: Community                                                |
        | Git Commit Hash: 6831e487a84c8bde625de8c73feec9e6ec02f426         |
        | Git Branch: master                                                |
        | UTC Build Time: 2020-08-23 13:37:28                               |
        | GoVersion: go1.13                                                 |
        | Race Enabled: false                                               |
        | TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
        | Check Table Before Drop: false                                    |
        +-------------------------------------------------------------------+
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `dumpling.log` for Dumpling if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - running command for Dumpling if possible

**Comment by lichunzhu** [comment]
Could you please run `show create table 0247__TICASE_1512_WWSVHA.t` and list the result in this issue?

**Comment by kennytm** [comment]
the SQL is 

```sql
SELECT  FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1
```

maybe all columns are generated 🤔 

```sql
create table a (a int as (1));
insert into a values (), (), ();
```

**Comment by kennytm** [comment]
leaving this up for contributors for 7 days. 

suggestion: use TDD. build dumpling and then test against the example table above, fixing any SQL error you encountered, until the correct output is produced.

basically you need to handle the case where `fields` is an empty string, starting from

https://github.com/pingcap/dumpling/blob/42ac4de0db6b1d153fd4beac489688a72ca0b0c1/v4/export/sql.go#L259-L267

**Comment by Abingcbc** [comment]
@kennytm I would like to take this one. I have finished the work and I have tested the example above. It works well.

```
Release version: v4.0.7-5-g1004016-dev
Git commit hash: 1004016d3d49ffaeb904920de697c883b71278dc
Git branch:      master
Build timestamp: 2020-10-18 07:02:33Z
Go version:      go version go1.15.2 darwin/amd64

[2020/10/18 15:02:39.739 +08:00] [INFO] [config.go:178] ["detect server type"] [type=TiDB]
[2020/10/18 15:02:39.739 +08:00] [INFO] [config.go:196] ["detect server version"] [version=4.0.0-beta.2-1178-g449587a08-dirty]
[2020/10/18 15:02:39.739 +08:00] [WARN] [dump.go:105] ["If the amount of data to dump is large, criteria: (data more than 60GB or dumped time more than 10 minutes)\nyou'd better adjust the tikv_gc_life_time to avoid export failure due to TiDB GC during the dump process.\nBefore dumping: run sql `update mysql.tidb set VARIABLE_VALUE = '720h' where VARIABLE_NAME = 'tikv_gc_life_time';` in tidb.\nAfter dumping: run sql `update mysql.tidb set VARIABLE_VALUE = '10m' where VARIABLE_NAME = 'tikv_gc_life_time';` in tidb.\n"]
[2020/10/18 15:02:39.748 +08:00] [WARN] [block_allow_list.go:15] ["unsupported dump schema in TiDB now"] [schema=METRICS_SCHEMA]
[2020/10/18 15:02:39.749 +08:00] [WARN] [block_allow_list.go:15] ["unsupported dump schema in TiDB now"] [schema=PERFORMANCE_SCHEMA]
[2020/10/18 15:02:39.749 +08:00] [WARN] [block_allow_list.go:15] ["unsupported dump schema in TiDB now"] [schema=mysql]
[2020/10/18 15:02:39.749 +08:00] [WARN] [block_allow_list.go:15] ["unsupported dump schema in TiDB now"] [schema=INFORMATION_SCHEMA]
[2020/10/18 15:02:39.763 +08:00] [INFO] [dump.go:249] ["Skip to dump data of table tidb_test.a, because all of its columns are generated"]
[2020/10/18 15:02:39.767 +08:00] [INFO] [main.go:229] ["dump data successfully, dumpling will exit now"]

```

But when I tried to add a unit test case, it seems that there is something wrong with the mock db.

```
SELECT COLUMN_NAME,EXTRA FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=? AND TABLE_NAME=? ORDER BY ORDINAL_POSITION;: all expectations were already fulfilled, call to Query 'SELECT COLUMN_NAME,EXTRA FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=? AND TABLE_NAME=? ORDER BY ORDINAL_POSITION;' with args [{Name: Ordinal:1 Value:test} {Name: Ordinal:2 Value:a}] was not expected ("SELECT COLUMN_NAME,EXTRA FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=? AND TABLE_NAME=? ORDER BY ORDINAL_POSITION;: all expectations were already fulfilled, call to Query 'SELECT COLUMN_NAME,EXTRA FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=? AND TABLE_NAME=? ORDER BY ORDINAL_POSITION;' with args [{Name: Ordinal:1 Value:test} {Name: Ordinal:2 Value:a}] was not expected")
```

This function causes the error. 
https://github.com/pingcap/dumpling/blob/1004016d3d49ffaeb904920de697c883b71278dc/v4/export/sql.go#L523

Is the reason because data-dog's sqlmock doesn't support table with all generated columns? Should I raise a new issue or just skip the unit test and raise my PR?

Thanks!

**Comment by lance6716** [comment]
maybe you could raise your current PR to give more information 😜

**Comment by Abingcbc** [comment]
> maybe you could raise your current PR to give more information 😜

Thanks for your reply! I have raised my PR. I have committed my unit test code, but it cannot pass. After figuring out the reason of error above, I will modify the code.
