### ISSUE TITLE
Maybe we need quote table names when querying DB info.

### ISSUE THREAD

**Issue by YuJuncen** [pingcap/dumpling#73]
Currently, we inject table name directly into sql query. 

https://github.com/pingcap/dumpling/blob/62b84147a330b6975a80d3133b320190a3c7a304/v4/export/sql.go#L37

https://github.com/pingcap/dumpling/blob/62b84147a330b6975a80d3133b320190a3c7a304/v4/export/sql.go#L50

Even those table names are get by connection from database directly, so we don't need to fear SQL injection attack. But when there are tables using key words of SQL, dumpling will fail, a example is run integration_test on MariaDB:

```
dump failed: SHOW CREATE DATABASE rows: err = Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows' at line 1
goroutine 1 [running]:
runtime/debug.Stack(0x1615be0, 0xc00000e4e0, 0x1616980)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/pingcap/dumpling/v4/export.withStack(0x1615be0, 0xc00000e4e0, 0xc0000260c0, 0xc0000243e0)
	/Users/hillium/Developer/dumpling/v4/export/error.go:40 +0x8d
github.com/pingcap/dumpling/v4/export.simpleQuery(0xc0001f4180, 0xc0000243e0, 0x19, 0xc0001858c0, 0x1, 0xc0000243e0)
	/Users/hillium/Developer/dumpling/v4/export/sql.go:367 +0x152
github.com/pingcap/dumpling/v4/export.ShowCreateDatabase(0xc0001f4180, 0x7ffeefbff7b5, 0x4, 0xc0001859e0, 0x14200df, 0x7ffeefbff7c1, 0x26)
	/Users/hillium/Developer/dumpling/v4/export/sql.go:38 +0x10c
github.com/pingcap/dumpling/v4/export.dumpDatabases(0x1620180, 0xc0000260c0, 0xc0001b4780, 0xc0001f4180, 0x161e3c0, 0xc000010078, 0x0, 0x100)
	/Users/hillium/Developer/dumpling/v4/export/dump.go:109 +0x124
github.com/pingcap/dumpling/v4/export.Dump(0xc0001b4780, 0x0, 0x0)
	/Users/hillium/Developer/dumpling/v4/export/dump.go:92 +0x84f
main.run()
	/Users/hillium/Developer/dumpling/cmd/dumpling/main.go:122 +0x5b9
main.glob..func1(0x19774e0, 0xc0001ec600, 0x0, 0x10)
	/Users/hillium/Developer/dumpling/cmd/dumpling/main.go:58 +0x20
github.com/spf13/cobra.(*Command).execute(0x19774e0, 0xc000020130, 0x10, 0x11, 0x19774e0, 0xc000020130)
	/Users/hillium/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x19774e0, 0x0, 0x1, 0xc00007a058)
	/Users/hillium/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/hillium/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
	/Users/hillium/Developer/dumpling/cmd/dumpling/main.go:131 +0x2d
```

**Comment by kennytm** [comment]
Duplicate of #73.
